train_input:
    data_dir: "./data/mnist/train"
    batch_size: 64
    drop_last_batch: True
    shuffle: True

eval_input:
    data_dir: "./data/mnist/val"
    batch_size: 64
    drop_last_batch: True
    shuffle: False

model:
    name: "fc_mnist_snntorch"
    beta: 0.95
    num_hidden: 1000
    num_outputs: 10
    num_steps: 25
    mixed_precision: False
    dropout: 0.0
    use_float16: False

optimizer:
    optimizer_type: "adam"
    learning_rate: 5e-4
    betas: (0.9, 0.999)

runconfig:
    max_steps: 5000
    checkpoint_steps: 200
    log_steps: 50
    seed: 1
    save_losses: True
